### ISSUE TITLE
Refactor AlamedaService CRD

### ISSUE THREAD

**Issue by tsungming** [containers-ai/federatorai-operator#13]
AlamedaService need support:
* Alameda Version
* Alameda excution (on/off) 
* GUI (on/off)

**Comment by mamafun** [comment]
we also need
- loglevel
  This is to set the loglevel of deployed alameda components. Default set to Info?
- prometheusService
  This should provide information to connect to a Prometheus service. Including endpoint and access credentials
- persistentVolumeClaim
  This is optional. It provides PVs for gui, ai and db(that keeps prediction metrics).

**Comment by prophetstor-ai** [comment]
@kfdev170707 help to defined the spec and add an example.

**Comment by tsungming** [comment]
@kfdev170707 help to defined the spec and add an example.
