### ISSUE TITLE
set default Alameda component image pull addresses to Redhat container registry and support env variables to overwrite it

### ISSUE THREAD

**Issue by mamafun** [containers-ai/federatorai-operator#132]
First we set default Alameda component image pull addresses to Redhat container registry
and we can overwrite the default address by env variables for testing purpose.
TBD the Redhat container registry addresses.

**Comment by rax845163** [comment]
@mamafun 
Do you mean to provide environment variables to overwrite image pull registry or each components' image name?

**Comment by jasonhuangprophet** [comment]
verified
