### ISSUE TITLE
Alameda-grafana route should be created automaticlly

### ISSUE THREAD

**Issue by jeantung** [containers-ai/federatorai-operator#135]
Alameda-grafana route should be created automaticlly when federatorai-operator installation is done successfully.

[Environment]
federatorai-operator version: 0.0.1

![image](https://user-images.githubusercontent.com/38522441/57125406-e6342600-6dbb-11e9-8df5-014f0e27e3a6.png)

**Comment by rax845163** [comment]
@tsungming @mamafun 
I remember we had disscussed that federatorai-operator creates native k8s resources.
Is there a need to create openshift resources?

**Comment by jasonhuangprophet** [comment]
duplicate to #171
