### ISSUE TITLE
CPU recommendation is stopped, but prediction is working fine and continuous

### ISSUE THREAD

**Issue by jeantung** [containers-ai/federatorai-operator#136]
[Actaul Results]
Some pods' CPU recommendation are stopped, and no more message "Write recommendation result" of these pods's CPU in alameda-ai.log, but prediction is still working fine, message "POD_prediction Write containers predicted data" can be found in alameda-ai.log and DB.

[Environment]
Openshift cluster master: 172.31.11.129; root/password; GUI login: root/password
Openshift node: 172.31.11.130; root/password
federatorai-operator version: 0.1.0
alameda-ai version: v0.3.8-5
alameda-operator version: v0.3.8-5

![image](https://user-images.githubusercontent.com/38522441/57128250-66ab5480-6dc5-11e9-986c-c026e7626e9b.png)
![image](https://user-images.githubusercontent.com/38522441/57128259-6ad77200-6dc5-11e9-95d7-9f6e1e92bd35.png)
![image](https://user-images.githubusercontent.com/38522441/57128873-598f6500-6dc7-11e9-9ee7-615edf6ac244.png)

**Comment by rax845163** [comment]
I inspected the recommendation in database and found that the recommendation existing.
![Screen Shot 2019-05-06 at 12 38 32 PM](https://user-images.githubusercontent.com/2918565/57206938-2c77c800-6ffc-11e9-9841-ef50beb2993a.png)

**Comment by jasonhuangprophet** [comment]
verified
