### ISSUE TITLE
federatorai-operator pod  crash loopbackoff when openshift 3.9

### ISSUE THREAD

**Issue by ekko771** [containers-ai/federatorai-operator#150]
[root@node17129 upstream]# oc logs -f federatorai-operator-5449bc67ff-8d2b4

2019-05-15T08:49:32.021Z    INFO    manager    Go Version: go1.11.9

2019-05-15T08:49:32.021Z    INFO    manager    Go OS/Arch: linux/amd64

2019-05-15T08:49:32.021Z    INFO    manager    Federatorai Operator Version: federatorai-operator HEAD-ae5fee9

2019-05-15T08:49:32.021Z    INFO    manager    {

    "WatchNamespace": "",

    "Metrics": {

        "Host": "0.0.0.0",

        "Port": 8383

    },

    "Log": {

        "OutputLevel": "info",

        "OutputPaths": [

            "stdout",

            "/var/log/alameda/federatorai-operator.log"

        ]

    }

}

2019-05-15T08:49:32.021Z    INFO    leader    Trying to become the leader.

2019-05-15T08:49:32.110Z    INFO    leader    No pre-existing lock was found.

2019-05-15T08:49:32.113Z    ERROR    leader    Unknown error creating ConfigMap    {"error": "configmaps \"federatorai-operator-lock\" is forbidden: cannot set an ownerRef on a resource you can't delete: User \"system:serviceaccount:federatorai:federatorai-operator\" cannot delete configmaps in project \"federatorai\", <nil>"}

github.com/containers-ai/federatorai-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error

    /go/src/github.com/containers-ai/federatorai-operator/vendor/github.com/go-logr/zapr/zapr.go:128

github.com/containers-ai/federatorai-operator/vendor/github.com/operator-framework/operator-sdk/pkg/leader.Become

    /go/src/github.com/containers-ai/federatorai-operator/vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go:132

main.main

    /go/src/github.com/containers-ai/federatorai-operator/cmd/manager/main.go:143

runtime.main

    /usr/local/go/src/runtime/proc.go:201

2019-05-15T08:49:32.114Z    ERROR    manager        {"error": "configmaps \"federatorai-operator-lock\" is forbidden: cannot set an ownerRef on a resource you can't delete: User \"system:serviceaccount:federatorai:federatorai-operator\" cannot delete configmaps in project \"federatorai\", <nil>"}

github.com/containers-ai/federatorai-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error

    /go/src/github.com/containers-ai/federatorai-operator/vendor/github.com/go-logr/zapr/zapr.go:128

main.main

    /go/src/github.com/containers-ai/federatorai-operator/cmd/manager/main.go:145

runtime.main

    /usr/local/go/src/runtime/proc.go:201

[Environment]
Openshift  version: 3.9
Openshift node: 172.31.17.129; root/password
federatorai-operator version: 0.2.0

**Comment by ekko771** [comment]
fix #153

**Comment by mamafun** [comment]
Note: the solution is to add the missing but required "delete" permissions.
BTW, we may also need to add the changes in olm CSV.

**Comment by jasonhuangprophet** [comment]
issue occurred in v0.2.15 on OKD 3.9

**Comment by jeantung** [comment]
Deploy alamda is failed on Openshift 3.9 .

alameda-operator log: 
 grpc: addrConn.createTransport failed to connect to {alameda-datahub.federatorai.svc:50050 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.30.62.109:50050: connect: no route to host". 

 oc describe pod alameda-operator-6f6d6d4ff5-xbw66  : 
![Image 1](https://user-images.githubusercontent.com/38522441/59843154-8fde6f00-938a-11e9-8435-005ec509ddfe.png)
![Image 2](https://user-images.githubusercontent.com/38522441/59843179-98cf4080-938a-11e9-9fdb-ba88ac25ec1e.png)
![Image 3](https://user-images.githubusercontent.com/38522441/59843194-9ff64e80-938a-11e9-9f49-75f140a4c1fe.png)


oc describe pod admission-controller-5b87ff69fb-2mzs4  :  

![Image 4](https://user-images.githubusercontent.com/38522441/59843510-48a4ae00-938b-11e9-8d03-73de6fbfab65.png)
![Image 5](https://user-images.githubusercontent.com/38522441/59843513-4b070800-938b-11e9-8f39-1dbd67c737b5.png)


alameda-influxdb:

![Image 6](https://user-images.githubusercontent.com/38522441/59843716-b3ee8000-938b-11e9-85e0-f3de77f1414e.png)
![Image 7](https://user-images.githubusercontent.com/38522441/59843723-b650da00-938b-11e9-9565-26f3c220b3be.png)



**Environment:**
OKD v3.9 master: 172.31.3.56
federatorai-operator: 0.2.17
alameda version: 0.3.31

**Comment by ekko771** [comment]
please change alamedaservice prometheusservice to https://prometheus.openshift-metrics:443

**Comment by jasonhuangprophet** [comment]
Hi Jean,Please help to verify with Kroos's comment

**Comment by jeantung** [comment]
Verified.
Deploy alameda with "prometheusservice: https://prometheus.openshift-metrics:443" in alamedaservice.yaml is working well. 

**Environment:**
federatorai-operator: 0.2.17
alameda version: 0.3.33
