### ISSUE TITLE
Unable to install on OpenShift 4.1.3

### ISSUE THREAD

**Issue by mrhillsman** [containers-ai/federatorai-operator#233]
Hi,

I work on the Operator Enablement team at Red Hat and am unable to install this operator via the OpenShift embedded operatorhub with the following notes:

Created alameda namespace|project as system:admin via OpenShift dashboard

Created AlamedaService with the following changes:

selfDriving: true
prometheusService: <my_prometheus_url>:9091

Errors after creating AlamedaService:

alameda-ai - Unschedulable
- 0/6 nodes are available
  - 3 insufficient CPU, 3 taints pod does not tolerate
  - “resolved” by setting the CPU request from 2 to 50m in the Deployment

admission-controller - ContainersNotReady
- failed to connect to alameda-datahub.alameda.svc:50050
  - no route to host (172.30.54.247:50050)

alameda-evictioner - ContainersNotReady
- same error re no route to host

alameda-operator - ContainersNotReady
- same error re no route to host

alameda-datahub - pod the others are trying to connect to
- 2019-07-10T23:09:08.165355Z	info	cluster_status_db_measurement	cluster_status/node.go:96	Query nodes in cluster: SELECT * FROM node WHERE "in_cluster"=true 
- 2019-07-10T23:09:08.174165Z	error	gRPC	datahub/server.go:455	list alameda nodes failed: list alameda nodes from influxdb failed: database not found: alameda_cluster_status
- 2019-07-10T23:09:08.175567Z	info	transport: http2Server.HandleStreams failed to read frame: read tcp [::1]:50050->[::1]:42620: read: connection reset by peer
- 2019-07-10T23:09:08.175641Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"

Trying a new AlamedaService (selfDriving: false):
- 2019-07-11T14:27:44.871071Z	error	gRPC	datahub/server.go:162	Post https://alameda-influxdb.alameda.svc:8086/query?db=alameda_prediction&params=null&q=CREATE+DATABASE+alameda_prediction: dial tcp 172.30.179.215:8086: connect: no route to host
- 2019-07-11T14:27:45.895748Z	error	gRPC	datahub/server.go:167	Post https://alameda-influxdb.alameda.svc:8086/query?db=alameda_prediction&params=null&q=ALTER+RETENTION+POLICY+%22autogen%22+on+%22alameda_prediction%22+DURATION+30d+SHARD+DURATION+1d: dial tcp 172.30.179.215:8086: connect: connection refused
- 2019-07-11T14:27:45.901345Z	error	gRPC	datahub/server.go:162	Post https://alameda-influxdb.alameda.svc:8086/query?db=alameda_recommendation&params=null&q=CREATE+DATABASE+alameda_recommendation: dial tcp 172.30.179.215:8086: connect: connection refused
- 2019-07-11T14:27:45.911976Z	error	gRPC	datahub/server.go:167	Post https://alameda-influxdb.alameda.svc:8086/query?db=alameda_recommendation&params=null&q=ALTER+RETENTION+POLICY+%22autogen%22+on+%22alameda_recommendation%22+DURATION+30d+SHARD+DURATION+1d: dial tcp 172.30.179.215:8086: connect: connection refused
- 2019-07-11T14:27:45.917466Z	error	gRPC	datahub/server.go:162	Post https://alameda-influxdb.alameda.svc:8086/query?db=alameda_score&params=null&q=CREATE+DATABASE+alameda_score: dial tcp 172.30.179.215:8086: connect: connection refused
- 2019-07-11T14:27:45.923812Z	error	gRPC	datahub/server.go:167	Post https://alameda-influxdb.alameda.svc:8086/query?db=alameda_score&params=null&q=ALTER+RETENTION+POLICY+%22autogen%22+on+%22alameda_score%22+DURATION+30d+SHARD+DURATION+1d: dial tcp 172.30.179.215:8086: connect: connection refused
- 2019-07-11T14:27:45.923852Z	info	gRPC	datahub/server.go:108	starting gRPC server
- 2019-07-11T14:27:45.923989Z	info	gRPC	datahub/server.go:114	gRPC server listening on :50050

I assume the initial failing is due to the alameda-datahub container being up before alameda-influxdb is available because not long after the connection is no longer refused but rather there is an error related to database missing. Recreating the pod alameda-datahub did not work as I did not see the pod’s container attempt to create the databases alameda_cluster_status

In the server.go file I find:

databaseList := []string {
	“alameda_prediction”,
	“alameda_recommendation”,
	“alameda_score”,
}

So I am wondering if alameda_cluster_status should be added to databaseList but either way I have also sent an email to support@prophetstor.com

**Comment by mrhillsman** [comment]
@cheesiong-lee

**Comment by HungoHung** [comment]
Hi Melvin,

Thank you for posting this issue.

-  **About alameda-ai pod:**
      Yes, we do add cpu requirement of alameda-ai pod to 2 cores, you can reduce this for testing purpose.

-  **About admission-controller, alameda-evictioner, alameda-operator:**
      Many of alameda pods rely on alameda-datahub service, so those pods will in NotReady state if datahub itself is not ready.

-  **About alameda-datahub:**
      The database missing error because of alameda-operator use alameda-datahub service to write data into alameda-influxdb. However, alameda-datahub itself can't pass the **readiness probe** so the datahub service is not available, and in consequence InfluxDB db has no needed data.
      In most case, alameda-datahub can't pass readiness probe is due to **prometheusService** setting inside AlamedaService CR has wrong information.

Please help to provide following info for further diagnosis:

**1. Use "oc describe pod <your datahub pod>" to see if msg like below appeared and show us the prometheusService setting.**

- Warning  Unhealthy  40m                  kubelet, node17133  Readiness probe failed: 2019-07-12T02:10:45.555620Z                                  error  probe  probe/probe.go:33  Readiness probe: query failed due to list pod metrics failed: list pod container cpu usage metric by namespaced name failed: prometheus query_range failed: send http request failedGet https://prometheus-k8sWrong.openshift-monitoring:9091/api/v1/query_range?end=1562897445&query=namespace_pod_name_container_name%3Acontainer_cpu_usage_seconds_total%3Asum_rate%7Bpod_name+%21%3D+%22%22%2Ccontainer_name+%21%3D+%22POD%22%7D&start=0&step=30: dial tcp: lookup prometheus-k8sWrong.openshift-monitoring on 172.31.17.133:53: no such host

     In above msg,**prometheusService** consists of https://prometheus-k8sWrong(prometheus svc).openshift-monitoring(prometheus namespace):9091(port).

**2. Use "oc get svc -n <prometheus namespace>" to list the prometheus services in your env.**

**Comment by mrhillsman** [comment]
Hi @HungoHung 

I am confident the issue is not related to failed readiness probe due to prometheus URL misconfiguration. When setting the alameda-datahub deployment to 0 then to 1 the alameda-datahub pod is recreated and then the following error is reported:

```shell
2019-07-12T04:52:54.369230Z info cluster_status_db_measurement cluster_status/node.go:96 Query nodes in cluster: SELECT * FROM node WHERE "in_cluster"=true
2019-07-12T04:52:54.381389Z error gRPC datahub/server.go:455 list alameda nodes failed: list alameda nodes from influxdb failed: database not found: alameda_cluster_status
2019-07-12T04:52:54.384780Z info transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

And checking the alameda-influxdb pod the previously mentioned databases that were not created are created:

```shell
~ $ influx -ssl -unsafeSsl -username admin -password adminpass -execute 'show databases'
name: databases
name
----
_internal
alameda_prediction
alameda_recommendation
alameda_score
~ $
```

The actual database name is only found in two files:

```shell
MacBook-Pro:federatorai-operator mhillsma$ grep -iRl alameda_cluster_status ./*
./assets/ConfigMap/dashboards-config.yaml
./vendor/github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/const.go
MacBook-Pro:federatorai-operator mhillsma$ grep -iRl 'ClusterStatus Database' ./*
./vendor/github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/const.go
```

```shell
MacBook-Pro:openshift mhillsma$ ./oc describe pod alameda-datahub-66b6675d46-ldqr2 -n alameda

Events:
  Type     Reason            Age                From                                  Message
  ----     ------            ----               ----                                  -------
  Normal   Scheduled         106s               default-scheduler                     Successfully assigned alameda/alameda-datahub-66b6675d46-ldqr2 to ip-10-0-129-79.ec2.internal
  Warning  FailedScheduling  106s               default-scheduler                     Binding rejected: Operation cannot be fulfilled on pods/binding "alameda-datahub-66b6675d46-ldqr2": pod alameda-datahub-66b6675d46-ldqr2 is already assigned to node "ip-10-0-129-79.ec2.internal"
  Normal   Pulled            98s                kubelet, ip-10-0-129-79.ec2.internal  Container image "quay.io/prophetstor/alameda-datahub-ubi:v4.1.39" already present on machine
  Normal   Created           98s                kubelet, ip-10-0-129-79.ec2.internal  Created container alameda-datahub
  Normal   Started           98s                kubelet, ip-10-0-129-79.ec2.internal  Started container alameda-datahub
  Warning  Unhealthy         92s                kubelet, ip-10-0-129-79.ec2.internal  Readiness probe failed: 2019-07-12T04:12:13.289804Z  error  probe  probe/probe.go:27  Readiness probe: ping influxdb failed due to exit status 7
  Warning  Unhealthy         4s (x17 over 84s)  kubelet, ip-10-0-129-79.ec2.internal  Readiness probe errored: rpc error: code = Unknown desc = command error: command timed out, stdout: , stderr: , exit code -1
```

**Comment by mamafun** [comment]
Hi @mrhillsman 
The "alameda_cluster_status"  database will be created by datahub when datahub received POST command and it does not exist in the InfluxDB.
So this could be another issue and need more information from you to see what would be the cause.
Could you please provide the log by the following command?
```
oc logs alameda-operator-xxxx-xx -n alameda
oc get nodes -o yaml
oc get pods --all-namespaces
```
Thanks

**Comment by mrhillsman** [comment]
@mamafun unfortunately I do not have the operator installed and have moved on to the next one but from looking at the Github code repo as previously mentioned I do not see the missing database being created.

**Comment by mamafun** [comment]
hi @mrhillsman,
I found the code that creates missing database is at `func WritePoints()` in file `./vendor/github.com/containers-ai/alameda/datahub/pkg/repository/influxdb/influxdb.go` where you can see that
```
        if strings.Contains(err.Error(), "database not found") {
            if err = influxDBRepository.CreateDatabase(bpCfg.Database); err != nil {
                scope.Error(err.Error())
                return err
            } else {
                err = influxDBRepository.WritePoints(points, bpCfg)
            }
        }
```
Therefore it should create the database if it is not there. 
Anyway please pin me if you have a chance to test it again. It would be very thankful if you can provide the test logs. Thanks again for your trying out.

**Comment by mrhillsman** [comment]
@mamafun I was able to get the datahub pod working by removing the port from the prometheusService field in the spec when updating it to use the URL where prometheus is for the cluster:

prometheusService: 'https://prometheus-k8s.openshift-monitoring:9091'

**Comment by mamafun** [comment]
@mrhillsman 
Thank you for reporting this.
I am just curious that are there new changes about Prometheus in the latest OpenShift?
Things like the Prometheus proxy service/container port is changed from 9091 to 443/8443?
