### ISSUE TITLE
Example configuration for AlamedaScaler kind in the operatorhub page

### ISSUE THREAD

**Issue by 4n4nd** [containers-ai/federatorai-operator#379]
I was trying to install the operator from operatorhub, and I couldn't find any documentation for how to set up an alamedascaler in the operatorhub page or the github page listed there.

Could guys please add a sample alamedascaler configuration on that page? or maybe in the README of this repo?

**Comment by jasonhuangprophet** [comment]
Hi 4n4nd
Please check the link of QuickStart Guide at right side in operatorhub page as the attached screenshot.
![image](https://user-images.githubusercontent.com/36724328/65100681-b6985a00-d9fa-11e9-9354-41b69dfc602f.png)
You can find the AlamedaScaler link in the Quickstart Guide.
https://github.com/containers-ai/alameda/blob/master/design/crd_alamedascaler.md

And thanks for your comments, we'll add the document in operatorhub page.

**Comment by 4n4nd** [comment]
Thanks! I was able to find it, but it might have been easier to be able to just copy it from the operatorhub page.
I will close this issue then
