### ISSUE TITLE
Support Custom PersistentVolumeClaim definition

### ISSUE THREAD

**Issue by tsungming** [containers-ai/federatorai-operator#4]
Reference:
https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#custom-persistentvolumeclaim-definition

https://github.com/coreos/etcd-operator/blob/master/pkg/cluster/cluster.go#L372

https://github.com/coreos/etcd-operator/blob/master/pkg/util/k8sutil/k8sutil.go#L285

**Comment by mamafun** [comment]
We provide PV for components:
- alameda-ai
- influxdb
- grafana
- others?

**Comment by tsungming** [comment]
resolved by https://github.com/containers-ai/federatorai-operator/commit/61ee3a66c58814eee717b040fe4fbe29c11711e9#diff-c8b31fb9123c19a1d670026a66a45cb8
