### ISSUE TITLE
[Bug] Uninstall federator operator and delete alamedaservice doesn't clean up one of service

### ISSUE THREAD

**Issue by HungoHung** [containers-ai/federatorai-operator#80]
Steps:
After clicking uninstall federator operator and delete alamedaservice, there is still one service remain in system.

[root@node17133 ~]# oc get all
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/operator-admission-service   ClusterIP   172.30.180.168   <none>        443/TCP   1d

**Comment by mamafun** [comment]
Since Federator.ai Operator add owner references to every service objects it creates, this issue should be fixed. Please see if the issue still there. thanks.

**Comment by HungoHung** [comment]
Verified.
